pygments: true
url: http://connolly.io
lsi: false
exclude: [LICENSE, CNAME, colors.txt, README.md, .gitignore]
markdown: kramdown

permalink: /posts/:title

links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: Friends
    url: /friends/
  - title: Talks
    url: /talks/

theme:
  highlight_color: '#6F5499'

  social:
    github: NSNO
    twitter: ianconnolly

  name: Ian Connolly
  email: ian@connolly.io
  tagline: "the web. lambdas. cheesy pop-punk."

  google_analytics_key: UA-45598612-1

  show_disclaimer: true
